### ISSUE TITLE
图片显示效果改进

### ISSUE THREAD

**Issue by HuParry** [Floating-Ocean/hydrooj-pastebin-plus-fix#1]
轮播图在显示宽度较小高度较高的图片时，面板容易拉得很长。感觉可以加一个高度的配置选项，这样不会很突兀。

**Comment by Floating-Ocean** [comment]
你好，感谢提出issue，但是本仓库是hydrooj的剪贴板插件，理论上应该不会有轮播图吧（？）
不过如果的确存在问题，麻烦详细描述一下，谢谢。

**Comment by HuParry** [comment]
抱歉，发错了一个issue，应该是另一个仓库的。我先关闭本issue了，感谢回复。
